name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-lib:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Cache Maven packages for lib
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-lib-${{ hashFiles('lib/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-lib-

    - name: Build lib
      run: mvn -B package --file lib/pom.xml

    - name: Run tests for lib
      run: mvn test --file lib/pom.xml

    - name: Move and rename JAR for lib
      run: |
        mkdir -p lib/build
        mv lib/target/feature-flag-lib-1.0.0-jar-with-dependencies.jar lib/build/Feature-Flag-Lib.jar

  build-client:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Cache Maven packages for client
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-client-${{ hashFiles('client/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-client-

    - name: Build client
      run: mvn -B package --file client/pom.xml

    - name: Run tests for client
      run: mvn test --file client/pom.xml

    - name: Move and rename JAR for client
      run: |
        mkdir -p client/build
        mv client/target/feature-flag-client-1.0.0-jar-with-dependencies.jar client/build/Feature-Flag-Client.jar